const dotenv = require('dotenv');
dotenv.config();
const { 
  APP_PORT,HOST,USER,PASSWORD,DB,PORT,
  FRONTEND_URL,BACKEND_URL,PRODUCT_SERVICE,AUTH_SERVICE, 
  EMAIL_USER,EMAIL_PASSWORD,API_GATEWAY_URL

}= process.env;

module.exports = {
  APP_PORT,
  HOST,
  USER,
  PASSWORD,
  DB,
  PORT,
  FRONTEND_URL,
  BACKEND_URL,
  PRODUCT_SERVICE,
  AUTH_SERVICE,
  API_GATEWAY_URL,
  EMAIL_USER,
  EMAIL_PASSWORD
};